CREATE TABLE IF NOT EXISTS Person
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    create_dttm TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);